### ISSUE TITLE
Think of a good tagline

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/publishing-checklist#8]
We need a good tagline for this plugin. Ideas?

cc @mkeppel @joycectang @davisshaver @goldenapples

**Comment by goldenapples** [comment]
* Preflight for content
* Continuous integration for content
* Linting for content
* Your robot ombudsperson

Getting corny, I know.

**Comment by mkeppel** [comment]
- Did you get that? 
- Don't forget that! 
- You will never forget now


About as creative as I can get :)

**Comment by joycectang** [comment]
Where/how does the tagline appear?

**Comment by danielbachhuber** [comment]
> Where/how does the tagline appear?

This is just as a catchphrase for our project. It's not editorial-facing at all.

**Comment by davisshaver** [comment]
- WordPress Publishing Checklist
- WordPress Editorial Checklist
- Continuous Integration for Publishing
- PrePubBot
- PrePub
- PiedPiper

**Comment by davisshaver** [comment]
We're going with `Pre-flight your posts.`
